"""Initial migration.

Revision ID: 21281e4e28d8
Revises: 780889bd98aa
Create Date: 2021-05-01 07:22:23.906049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21281e4e28d8'
down_revision = '780889bd98aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=350), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('article')
    op.drop_table('discuss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discuss',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('body', mysql.VARCHAR(length=350), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('upload_date', mysql.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='discuss_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('article',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('body', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('upload_date', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('img_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='article_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('article_form')
    # ### end Alembic commands ###
