"""Initial migration.

Revision ID: 780889bd98aa
Revises: 8396f60b4af3
Create Date: 2021-05-01 07:14:09.999395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780889bd98aa'
down_revision = '8396f60b4af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discuss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=350), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discuss')
    # ### end Alembic commands ###
