"""Initial migration.

Revision ID: 8396f60b4af3
Revises: 0eddc4d2a496
Create Date: 2021-05-01 06:22:25.401009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8396f60b4af3'
down_revision = '0eddc4d2a496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('model', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'model')
    # ### end Alembic commands ###
